# Generated by Django 6.0.6 on 2026-06-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
