# Generated by Django 6.0.6 on 2026-06-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchsession_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='research_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
