# Generated by Django 6.0.6 on 2026-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchsession_research_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='fact_check_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
