# Generated by Django 6.0.6 on 2026-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchsession_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='final_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
